### ISSUE TITLE
What are the differences between this and the built-in jewish_calendar?

### ISSUE THREAD

**Issue by mikeage** [rt400/Jewish-Sabbaths-Holidays#3]
it wasn't clear to me from the README what advantages this offers (HebCal vs hdate, I guess... but so what?) the built in jewish_calendar integration

**Comment by disforw** [comment]
I was just wondering that myself, it seems like this one will allow you to choose your sensors where the other gives you the kitchen sink. Also I like the way this one breaks up “is_shabbat” and “is_yomtov” vs a single binary_sensor of “ issur_melacha_in_effect” in case you want to create 2 different sets of automation schedules.

**Comment by rt400** [comment]
As explained above, there are some significant differences between the two integrations.
1. I allow the calculation of the departure of Shabbat or Yom Tov according to the rising of the stars or according to a fixed time (40,50 ...)
2. The Torah portion of the week is always updated and does not appear only on Shabbat (I remember that this is how it exists but maybe they have already fixed it)
3. I allow dynamics between Shabbat and Yom Tov.
4. I am slowly making changes for example like counting the Omer (according to Nosah) and I have a few more ideas.

There are a few more differences, feel free to install what is convenient for you ..

**Comment by mikeage** [comment]
Ok, makes sense. Thanks for the explanation.

**Comment by mordhollander** [comment]
Does this one need an itnternet connection for running the automations?
As I think that jewish_calendar does not need a live internet connection to run the automations

**Comment by rt400** [comment]
My integration downloads data from the internet once a day and saves the data in a file and from there it works, to run the automations you don't need internet because it ran locally until the HA is restarted or the next day comes.
True, the JEWISH CALENDER does not use the internet, but who doesn't have internet available today. To run HA properly you must always be connected to the internet either way both work (at least mine works fine the other one I was informed that sometimes changes the name of the entity and adds numbers to it, i.e. doubles them and thus makes the automations not work).
Everyone will choose what is convenient for them, I built this integration long before the official one existed.
